name: mycompi
env: node
region: frankfurt
buildCommand: npm install && npx prisma generate
startCommand: node src/index.js
healthCheckPath: /health
headers:
  - name: Content-Security-Policy
    value: default-src 'self'; base-uri 'self'; font-src 'self' https://fonts.gstatic.com data:; form-action 'self'; frame-ancestors 'self'; img-src 'self' data: https://res.cloudinary.com https://fonts.googleapis.com https://fonts.gstatic.com; object-src 'none'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src-attr 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; upgrade-insecure-requests; connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; font-src https://fonts.gstatic.com
envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: JWT_REFRESH_SECRET
    sync: false
  - key: FRONTEND_URL
    value: "*"
  - key: PORT
    value: "3000"
